name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stargazers world map
        uses: lowlighter/metrics@master
        with:
          user: GH-X-ST
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.stargazers.worldmap.svg

          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200
          plugins_errors_fatal: yes
